# Generated by Django 4.1 on 2023-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), ('5+', '5+')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), ('5+', '5+')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='building_size_in_SQFT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
