# Generated by Django 4.1 on 2023-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_property_bathroom_property_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'watingapproval'), ('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
