# Generated by Django 4.1.3 on 2023-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_image_property_thumbnail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, upload_to='uploads/product_images'),
        ),
    ]
